### ISSUE TITLE
Custom functions do not show up in Excel on Mac

### ISSUE THREAD

**Issue by 1R053** [OfficeDev/Excel-Custom-Functions-JS#101]
# Expected behavior

When I download the repo, install and run it using npm the add in shows up in Excel for Mac. It is possible to start typing in a cell "=CONTOSO" and see all custom functions for that namespace.

# Current behavior

The addin shows up in the ribbon and the side panel loads. Also the command triggered from the sidepanel works. However, the custom functions do not show up in Excel cells.

## Steps to Reproduce

1. run the addin in Excel from npm
2. start typeing in an Excel cell =CONTOSO
3. ...no custom functions are found

## Context

* Operating System: MacOS Ventura
* Node version: 20.3.1
* Office version: Excel for Mac 16.74 (23061100)

## Failure Logs

no error messages reported

**Comment by Rick-Kirkham** [comment]
@1R053 Which branch of the repo are you in when you run with npm? (master or shared-runtime-master?)

**Comment by 1R053** [comment]
Hi @Rick-Kirkham - both of those branches don't seem to work for me on Mac

**Comment by millerds** [comment]
Have you tried deleting the cache (https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache)?

**Comment by 1R053** [comment]
yes, deleted it in the sidepane and using manual deletion instructions from the manual

**Comment by Rick-Kirkham** [comment]
Try creating a custom functions project with Yo Office instead of cloning the repo. See if you have the same symptoms on the generated project. It shouldn't matter whether you clone the repo or generate a project, but it would be an interesting data point, if there is any difference, so worth trying.

**Comment by 1R053** [comment]
that's what I tried first, in JS and TS using the shared runtime. Then I tried downloading it directly. Same problem

**Comment by Rick-Kirkham** [comment]
You can try [Runtime logging on Mac](https://learn.microsoft.com/office/dev/add-ins/testing/runtime-logging#runtime-logging-on-mac)

**Comment by Rick-Kirkham** [comment]
@1R053 Were you able to use runtime logging to fix this? I will close this due to inactivity in a few days.
