### ISSUE TITLE
How do you configure the Source Location Url?

### ISSUE THREAD

**Issue by Tom-H2oThermo** [OfficeDev/Excel-Custom-Functions-JS#122]
I have been unsuccessful in getting an answer from Microsoft support on how to fill in the SourceLocation URL, nobody seems to know how its supposed to be filled in.  I'm about to submit my app to the MS Partner Center and I'd like to avoid it getting rejected.  I think that what you are supposed to do is to create a deployment package as described here:
[Package Deployer tool - Power Platform | Microsoft Learn](https://learn.microsoft.com/en-us/power-platform/alm/package-deployer-tool?tabs=cli)
Then upload it to an Azure blob as described here.
https://learn.microsoft.com/en-us/power-platform/developer/appsource/store-package-azure-storage
and get a Shared Access signature URL.  But the Shared Access Signature URL has & symbols in it and when I paste it into my manifest, it doesn't work.  When I paste this into a webpage I get this error:
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:2da078d5-901e-0077-3ccc-8a45cd000000 Time:2024-04-09T22:22:38.2664093Z</Message>
<AuthenticationErrorDetail>Signature did not match. String to sign used was rl 2024-04-09T22:07:06Z 2024-04-10T22:07:06Z /blob/cs71003200312986c44/$root 2023-01-03 c </AuthenticationErrorDetail>
</Error>
I'm stuck...

**Comment by AlexJerabek** [comment]
@rundongmsft, could you please investigate?

**Comment by Tom-H2oThermo** [comment]
I think  I figured it out.  This site explains how to publish directly from VS Code.
https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code
I'll be working through this over the next few days.  Perhaps it would be helpful to others to have this repository have a pointer to this page.  Thanks for your response.

**Comment by Tom-H2oThermo** [comment]
From looking at the examples here:
https://github.com/umasubra/office-js-docs-1/blob/master/docs/overview/add-in-manifests.md
It appears that the SourceLocation url should be pointing at my taskpane.html hosted at an https site.  So, I think this issue can be closed (unless my understanding is not correct).

**Comment by AlexJerabek** [comment]
That is correct: the SourceLocation is where your task pane is hosted. To verify other details, please refer to the examples of Custom Functions projects in our sample repo: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Excel-custom-functions. Please let us know if you have any further questions.
