### ISSUE TITLE
How can we integrate custom functions into an existing .net web project

### ISSUE THREAD

**Issue by yowl** [OfficeDev/Excel-Custom-Functions-JS#47]
The Yeoman scaffolding is fine, but if you want to make json calls to an existing .net web project in Visual Studio, it's not clear what changes need to be made to get the sideloading working.

**Comment by millerds** [comment]
I'm not sure what you mean by "make json calls to an existing .net web project".  If this is still an issue, please re-open and explain a little more.

**Comment by yowl** [comment]
I don't know it was so long ago, we are not using it now.

**Comment by millerds** [comment]
Sorry for the extreme delayed response.

**Comment by yowl** [comment]
Its ok, I would like to look at this again, and if so I'll reopen the task if I remember and still hit the problem.
