### ISSUE TITLE
Generate functions dynamically

### ISSUE THREAD

**Issue by HughGrovesArup** [OfficeDev/Excel-Custom-Functions-JS#61]
Hi, I am wondering is it possible to generate javascript UDFs at runtime (perhaps at application load)? We currently do this using ExcelDNA but would be interested in switching to javascript for the improved 'BUSY' behaviour for slow requests.

**Comment by millerds** [comment]
See https://github.com/OfficeDev/Excel-Custom-Functions/issues/296 where more discussion has been going on.
